### ISSUE TITLE
Crop results should be ordered by guide count

### ISSUE THREAD

**Issue by warpling** [openfarmcc/OpenFarm#418] opened 2015-01-15 22:45 UTC
Requires reindexing the `guides_count` counter cache?

**Comment by simonv3** [comment] 2015-01-18 02:48
What does that involve? 

Does guides_count get automatically updated when a guide gets created? Maybe it should.

**Comment by simonv3** [comment] 2015-01-18 04:33
Just noticed that this is a duplicate of #395

**Closed by simonv3** 2015-01-18 04:33 UTC
Labels: enhancement, low hanging fruit, Search
